controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\Company;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['get'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        if (!Yii::$app->user->isGuest) { 
            if (Yii::$app->user->identity->status==9) {
                //если суперадмин то в модуль заказов админки
                return $this->redirect(['/admin/orders/index']);    
            } else {
                //иначе в кабинет заказов компании
                return $this->redirect(['/orders/index']);    
            }
            
        }else
        {
            return $this->redirect(['site/login']);
        }
    }

    /**
     * Login action.
     *
     * @return Response|string
     */

    public function actionOnline()
    {
        if (Yii::$app->request->isAjax) {
            \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            $company = Company::find()->where(['id'=>Yii::$app->user->identity->company_id])->one() ;
            if ($company->online == 0) {
                $company->online = 1;
                $company->save();
                return ['checked' => true,'q'=>$company->name];
            } else {
                $company->online = 0;
                $company->save();
                return ['checked' => false,'q'=>$company->name];
            }
        }
    }
    
    public function actionGetstatus()
    {
        if (Yii::$app->request->isAjax) {
            \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            $company = Company::find()->where(['id'=>Yii::$app->user->identity->company_id])->one() ;
                return ['status' => $company->online];
        }
    }

    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        
        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }
    

    
    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();
        $this->redirect(['login']);
    }


    public function actionPolicy()
    {
        echo "string";
        die;
        return $this->render('index', [
        ]);  
    }

    public function actionMenuPosition()
    {
        $session = Yii::$app->session;
        if($session['body'] == null | $session['body'] == 'small') $session['body'] = 'large';
        else $session['body'] = 'small';

        if($session['left'] == null | $session['left'] == 'small') $session['left'] = 'large';
        else $session['left'] = 'small';

    }
}

views/yii2-app/layouts/content.php
<?php
use yii\widgets\Breadcrumbs;
use app\widgets\Alert;

?>
<div class="content-wrapper">
    <!-- <section class="content-header">
        <?php /*if (isset($this->blocks['content-header'])) {*/ ?>
            <h1><?php /*$this->blocks['content-header']*/ ?></h1>
        <?php /*} else {*/ ?>
            <h1>
                <?php
                /*if ($this->title !== null) {
                    echo \yii\helpers\Html::encode($this->title);
                } else {
                    echo \yii\helpers\Inflector::camel2words(
                        \yii\helpers\Inflector::id2camel($this->context->module->id)
                    );
                    echo ($this->context->module->id !== \Yii::$app->id) ? '<small>Module</small>' : '';
                }*/ ?>
            </h1>
        <?php /*}*/ ?>

        <?php
        /*Breadcrumbs::widget(
            [
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]
        )*/ ?>
    </section> -->

    <section class="content">
        <?= Alert::widget() ?>
        <?= $content ?>
    </section>
</div>


<!-- Control Sidebar -->

<!-- Add the sidebar's background. This div must be placed
     immediately after the control sidebar -->

views/yii2-app/layouts/header-menu.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

?>

<header >
    <div class="wrapper">
        <div class="logo">
            <a href="<?=Url::toRoute([Yii::$app->homeUrl])?>"><h2><?=Yii::$app->name?></h2></a>
        </div>
        <div class="hdr_menu">            
        </div>
        <div class="hdr_rght">            
        </div>
        <div class="hamburger">
            <span></span>
            <span></span>
            <span></span>
        </div>            
    </div>         
</header>

views/yii2-app/layouts/header.php
<?php
use yii\widgets\Breadcrumbs;
use app\widgets\Alert;
use yii\helpers\Html;
use kartik\switchinput\SwitchInput;
use yii\web\View;


?>
<style>
.onoffswitch {
    margin-top: 10px;
    position: relative; width: 100px;
    -webkit-user-select:none; -moz-user-select:none; -ms-user-select: none;
}
.onoffswitch-checkbox {
    display: none;
}
.onoffswitch-label {
    display: block; overflow: hidden; cursor: pointer;
    border: 2px solid #999999; border-radius: 20px;
}
.onoffswitch-inner {
    display: block; width: 200%; margin-left: -100%;
    transition: margin 0.3s ease-in 0s;
}
.onoffswitch-inner:before, .onoffswitch-inner:after {
    display: block; float: left; width: 50%; height: 30px; padding: 0; line-height: 30px;
    font-size: 14px; color: white; font-family: Trebuchet, Arial, sans-serif; font-weight: bold;
    box-sizing: border-box;
}
.onoffswitch-inner:before {
    content: "OnLine";
    padding-left: 10px;
    background-color: #34A7C1; color: #FFFFFF;
}
.onoffswitch-inner:after {
    content: "OffLine";
    padding-right: 10px;
    background-color: #EEEEEE; color: #999999;
    text-align: right;
}
.onoffswitch-switch {
    display: block; width: 18px; margin: 6px;
    background: #FFFFFF;
    position: absolute; top: 0; bottom: 0;
    right: 66px;
    border: 2px solid #999999; border-radius: 20px;
    transition: all 0.3s ease-in 0s; 
}
.onoffswitch-checkbox:checked + .onoffswitch-label .onoffswitch-inner {
    margin-left: 0;
}
.onoffswitch-checkbox:checked + .onoffswitch-label .onoffswitch-switch {
    right: 0px; 
}
</style>

                
                <!-- START X-NAVIGATION VERTICAL -->
                <ul class="x-navigation x-navigation-horizontal x-navigation-panel">
                    <!-- TOGGLE NAVIGATION -->
                    <li class="xn-icon-button">
                        <a href="#" onclick="$.post('/site/menu-position');" class="x-navigation-minimize"><span class="fa fa-dedent"></span></a>
                    </li>
                    <!-- END TOGGLE NAVIGATION -->
                    <!-- SEARCH -->
                    <!-- <li class="xn-search">
                        <form role="form">
                            <input type="text" name="search" placeholder="Search..."/>
                        </form>
                    </li>   --> 
                    <!-- END SEARCH -->
                    <!-- SIGN OUT -->
                    <li class="xn-icon-button pull-right">
                        <?= Html::a('<span class="fa fa-sign-out"></span>',['/site/logout'],
                            ['data-confirm'=> false, 'data-method'=>false,
                            'data-request-method'=>'post','data-toggle'=>'tooltip',]) ?>
                    </li> 

                    <li id="togle-online" class="xn-icon-button pull-right">
                        <div class="onoffswitch">
                            <input onclick="online()" type="checkbox" name="onoffswitch" class="onoffswitch-checkbox" id="myonoffswitch" checked>
                            <label class="onoffswitch-label" for="myonoffswitch">
                                <span class="onoffswitch-inner"></span>
                                <span class="onoffswitch-switch"></span>
                            </label>
                        </div>
                    </li>
                    <!-- END SIGN OUT -->
                    <!-- MESSAGES -->
                    <!-- <li class="xn-icon-button pull-right">
                        <a href="#"><span class="fa fa-comments"></span></a>
                        <div class="informer informer-danger">4</div>
                        <div class="panel panel-primary animated zoomIn xn-drop-left xn-panel-dragging">
                            <div class="panel-heading">
                                <h3 class="panel-title"><span class="fa fa-comments"></span> Messages</h3>                                
                                <div class="pull-right">
                                    <span class="label label-danger">4 new</span>
                                </div>
                            </div>
                            <div class="panel-body list-group list-group-contacts scroll" style="height: 200px;">
                                <a href="#" class="list-group-item">
                                    <div class="list-group-status status-online"></div>
                                    <img src="/../examples/images/users/user2.jpg" class="pull-left" alt="John Doe"/>
                                    <span class="contacts-title">John Doe</span>
                                    <p>Praesent placerat tellus id augue condimentum</p>
                                </a>
                                <a href="#" class="list-group-item">
                                    <div class="list-group-status status-away"></div>
                                    <img src="/../examples/images/users/user.jpg" class="pull-left" alt="Dmitry Ivaniuk"/>
                                    <span class="contacts-title">Dmitry Ivaniuk</span>
                                    <p>Donec risus sapien, sagittis et magna quis</p>
                                </a>
                                <a href="#" class="list-group-item">
                                    <div class="list-group-status status-away"></div>
                                    <img src="/../examples/images/users/user3.jpg" class="pull-left" alt="Nadia Ali"/>
                                    <span class="contacts-title">Nadia Ali</span>
                                    <p>Mauris vel eros ut nunc rhoncus cursus sed</p>
                                </a>
                                <a href="#" class="list-group-item">
                                    <div class="list-group-status status-offline"></div>
                                    <img src="/../examples/images/users/user6.jpg" class="pull-left" alt="Darth Vader"/>
                                    <span class="contacts-title">Darth Vader</span>
                                    <p>I want my money back!</p>
                                </a>
                            </div>     
                            <div class="panel-footer text-center">
                                <a href="pages-messages.html">Show all messages</a>
                            </div>                            
                        </div>                        
                    </li> -->
                    <!-- END MESSAGES -->
                    <!-- TASKS -->
                    <!-- <li class="xn-icon-button pull-right">
                        <a href="#"><span class="fa fa-tasks"></span></a>
                        <div class="informer informer-warning">3</div>
                        <div class="panel panel-primary animated zoomIn xn-drop-left xn-panel-dragging">
                            <div class="panel-heading">
                                <h3 class="panel-title"><span class="fa fa-tasks"></span> Tasks</h3>                                
                                <div class="pull-right">
                                    <span class="label label-warning">3 active</span>
                                </div>
                            </div>
                            <div class="panel-body list-group scroll" style="height: 200px;">                                
                                <a class="list-group-item" href="#">
                                    <strong>Phasellus augue arcu, elementum</strong>
                                    <div class="progress progress-small progress-striped active">
                                        <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 50%;">50%</div>
                                    </div>
                                    <small class="text-muted">John Doe, 25 Sep 2014 / 50%</small>
                                </a>
                                <a class="list-group-item" href="#">
                                    <strong>Aenean ac cursus</strong>
                                    <div class="progress progress-small progress-striped active">
                                        <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%;">80%</div>
                                    </div>
                                    <small class="text-muted">Dmitry Ivaniuk, 24 Sep 2014 / 80%</small>
                                </a>
                                <a class="list-group-item" href="#">
                                    <strong>Lorem ipsum dolor</strong>
                                    <div class="progress progress-small progress-striped active">
                                        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="95" aria-valuemin="0" aria-valuemax="100" style="width: 95%;">95%</div>
                                    </div>
                                    <small class="text-muted">John Doe, 23 Sep 2014 / 95%</small>
                                </a>
                                <a class="list-group-item" href="#">
                                    <strong>Cras suscipit ac quam at tincidunt.</strong>
                                    <div class="progress progress-small">
                                        <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%;">100%</div>
                                    </div>
                                    <small class="text-muted">John Doe, 21 Sep 2014 /</small><small class="text-success"> Done</small>
                                </a>                                
                            </div>     
                            <div class="panel-footer text-center">
                                <a href="pages-tasks.html">Show all tasks</a>
                            </div>                            
                        </div>                        
                    </li> -->
                    <!-- END TASKS -->
                </ul>
                <!-- END X-NAVIGATION VERTICAL -->                    
                
                <!-- START BREADCRUMB -->
                <!-- <ul class="breadcrumb push-down-0">
                    <li><a href="#">Home</a></li>
                    <li><a href="#">Layouts</a></li>
                    <li class="active">Custom Navigation</li>                    
                </ul> -->

                <section class="breadcrumb push-down-0">
                <?php
               /* echo Breadcrumbs::widget(
                    [
                        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                    ]
                )*/ ?>
                <?php if (isset($this->blocks['content-header'])) { ?>
                    <h1><?php $this->blocks['content-header'] ?></h1>
                <?php } else { ?>
                    <!-- <h1>
                        <?php
                        /*if ($this->title !== null) {
                            echo \yii\helpers\Html::encode($this->title);
                        } else {
                            echo \yii\helpers\Inflector::camel2words(
                                \yii\helpers\Inflector::id2camel($this->context->module->id)
                            );
                            echo ($this->context->module->id !== \Yii::$app->id) ? '<small>Module</small>' : '';
                        }*/ ?>
                    </h1> -->
                <?php } ?>

            </section>

                <!-- END BREADCRUMB -->                           
                
                <!-- PAGE CONTENT WRAPPER -->
                <div class="page-content-wrap">
                <br>                    
                </div>
                <!-- END PAGE CONTENT WRAPPER -->

<?php
$this->registerJs(
    "$(function() {
            $.ajax({
       url: '".Yii::$app->request->baseUrl."/site/getstatus',
       type: 'post',
       success: function (data) {
               $('#myonoffswitch').prop('checked', data.status);
       }
  });    
        });",
    View::POS_READY,
    'my-button-handler'
);
    ?>           
    <script>
        
    function online(){
    $.ajax({
       url: '<?php echo Yii::$app->request->baseUrl. '/site/online' ?>',
       type: 'post',
       data: {
                _csrf : '<?=Yii::$app->request->getCsrfToken()?>'
             },
       success: function (data) {
           $("#myonoffswitch").prop('checked', data.checked);
          console.log(data.checked);
          console.log(data.q);
       }
  });    
    }
    
    </script>

views/yii2-app/layouts/header0.php
<?php
use yii\helpers\Html;
use yii\bootstrap\Modal;
use johnitvn\ajaxcrud\CrudAsset; 
use yii\helpers\Url;
use app\models\Users;

$user_id = Yii::$app->user->identity->id;
/*Yii::$app->db->createCommand()->update('users', ['active_date' => date('Y-m-d H:i:s')], [ 'id' => \Yii::$app->user->identity->id ])->execute();*/

?>

<header >

    <div class="wrapper">
        <div class="logo">
            <a href="<?=Url::toRoute([Yii::$app->homeUrl])?>"><h2><?=Yii::$app->name?></h2></a>
        </div>
        <div class="hdr_menu">
            <ul>
                <li class=""><?= Html::a('Рабочий стол', ['/#'], []); ?></li>
                <li class=""><?= Html::a('Резюме', ['/resume/index'], []); ?></li>
                <li class=""><?= Html::a('Анкеты', ['/questionary/index'], []); ?></li>
                <?php if(Yii::$app->user->identity->type == 0) { ?>
                <li class="dropdown">
                    <a href="#" class="open_toggle">Администратор <span class="caret"></span></a>
                    <ul class="dropdown_body">
                        <li><?= Html::a('Пользователи', ['/users/index'], []); ?></li>
                        <li><?= Html::a('Настройки', ['/settings/index'], []); ?></li>
                    </ul>
                </li>
                <?php } ?>
                <li class="dropdown">
                    <a href="#" class="open_toggle">Настройки <span class="caret"></span></a>
                    <ul class="dropdown_body">
                        <li><?= Html::a('Уведомление', ['/notification/index'], []); ?></li>
                        <li><?= Html::a('Ваканция', ['/vacancy/index'], []); ?></li>
                        <li><?= Html::a('Группа', ['/group/index'], []); ?></li>
                        <li><?= Html::a('Статус резюме', ['/resume-status/index'], []); ?></li>
                    </ul>
                </li>               
            </ul>
        </div>
        <div class="hdr_rght">
            <div class="navbar-custom-menu">

                <ul class="nav navbar-nav">
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <span><?=Yii::$app->user->identity->fio ?></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="user-header">
                                <img src="<?= 'http://' . $_SERVER['SERVER_NAME'] ?>/images/nouser.png" class="img-circle" alt="User Image"/>
                                <p> <?=Yii::$app->user->identity->fio ?> </p>
                            </li>
                            <li class="user-footer">
                                    <?= Html::a('Профиль', ['users/change', 'id' => Yii::$app->user->identity->id],
                                    ['role'=>'modal-remote','title'=> 'Профиль','class'=>'btn btn-default btn-flat']); ?>
                                    <?= Html::a(
                                        'Выход',
                                        ['/site/logout'],
                                        ['data-method' => 'post', 'class' => 'btn btn-default btn-flat']
                                    ) ?>
                            </li>
                        </ul>
                    </li>
                    
                </ul>
            </div>
        </div>
        <div class="hamburger">
            <span></span>
            <span></span>
            <span></span>
        </div>            
    </div>
         
</header>


<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    "size" => "modal-lg",
    "options" => [
        "tabindex" => false,
    ],
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>

views/yii2-app/layouts/left.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use app\models\Users;

 $path = 'http://' . $_SERVER['SERVER_NAME'].'/uploads/company/'.Yii::$app->user->identity->companyPicture;
 //        . '/images/users/avatar.jpg';
 
?>
<?php 
        $session = Yii::$app->session;
        if($session['left'] == null | $session['left'] == 'small') $left="x-navigation-minimized";
        else $left="x-navigation-custom";
    ?>
<!-- START PAGE SIDEBAR -->
            <div class="page-sidebar page-sidebar-fixed scroll">
                <!-- START X-NAVIGATION -->
                <ul class="x-navigation <?=$left?>">
                    <li class="xn-logo">
                        <a href="<?=Url::toRoute([Yii::$app->homeUrl])?>"><?=Yii::$app->name?></a>
                        <a href="#" class="x-navigation-control"></a>
                    </li>
                    <li class="xn-profile">
                        <a href="#" class="profile-mini">
                            <img src="<?=$path?>" alt="John Doe"/>
                        </a>
                        <div class="profile">
                            <div class="profile-image">
                                <img src="<?=$path?>" alt="John Doe"/>
                            </div>
                            <div class="profile-data">
                                <div class="profile-data-name"><?=Yii::$app->user->identity->fullname?></div>
                                <div class="profile-data-title"><?=Yii::$app->user->identity->getCurrentRole()?></div>
                            </div>

                        </div>                                                                        
                    </li>
                    
                    <li class="xn-title">Menu</li>
                   <li <?php if (Yii::$app->controller->id=='dash-board'){ echo ' class = "active" ';}?>>
                        <?= Html::a('<span class="fa fa-desktop"></span> <span class="xn-text">Показатели</span>', ['/dash-board/index'], []); ?>
                    </li> 
                    <li <?php if (Yii::$app->controller->id=='orders'){ echo 'class="active"';}?>>
                        <?= Html::a('<span class="glyphicon glyphicon-euro"></span> <span class="xn-text">Заказы</span>', ['/orders/index'], []); ?>
                    </li> 
                    <li <?php if (Yii::$app->controller->id=='product'){ echo 'class="active"';}?>>
                        <?= Html::a('<span class="glyphicon glyphicon-shopping-cart"></span> <span class="xn-text">Товары</span>', ['/product/index'], []); ?>
                    </li> 
                    <li <?php if (Yii::$app->controller->id=='company-rating'){ echo 'class="active"';}?>>
                        <?= Html::a('<span class="glyphicon glyphicon-signal"></span> <span class="xn-text">Отзывы</span>', ['/company-rating/index'], []); ?>
                    </li> 
                    <li <?php if (Yii::$app->controller->id=='users'){ echo 'class="active"';}?>>
                        <?= Html::a('<span class="fa fa-users"></span> <span class="xn-text">Пользователи</span>', ['/users/index'], []); ?>
                    </li>
                                
                </ul>
                <!-- END X-NAVIGATION -->
            </div>
            <!-- END PAGE SIDEBAR -->

views/yii2-app/layouts/main-login.php
<?php
use backend\assets\AppAsset;
use yii\helpers\Html;
use app\widgets\Alert;

/* @var $this \yii\web\View */
/* @var $content string */

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="body-full-height" >
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="login-container lightmode">

<?php $this->beginBody() ?>

	<?= Alert::widget() ?>
    <?= $content ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/yii2-app/layouts/main.php
<?php
use yii\helpers\Html;

    if (class_exists('backend\assets\AppAsset')) {
        backend\assets\AppAsset::register($this);
    } else {
        app\assets\AppAsset::register($this);
    }

if (Yii::$app->controller->action->id === 'login' || Yii::$app->controller->action->id === 'register' || Yii::$app->controller->id === 'default' || Yii::$app->controller->id === 'setting') { 
    echo $this->render( 'main-login', ['content' => $content] );
} else {
    ?>
    <?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>
    <?php 
        $session = Yii::$app->session;
        if($session['body'] == null | $session['body'] == 'small') $body="page-navigation-toggled page-container-wide";
        else $body="";
    ?>
    <body class="">
    <?php $this->beginBody() ?>
        <div class="page-container <?=$body ?>">

            <?= $this->render( 'left.php', [] ) ?>
            <!-- PAGE CONTENT -->
            <div class="page-content">
                <?= Yii::$app->controller->id == 'default' ? $this->render( 'header-menu.php', [] ) : $this->render( 'header.php', [] ) ?>
                <?= $this->render( 'content.php', ['content' => $content, ] ) ?>
             </div>                       
            <!-- END PAGE CONTENT -->
        </div>
    <?php $this->endBody() ?>
    </body>
    </html>
    <?php $this->endPage() ?>
<?php } ?>