models/Orders.php
<?php

namespace app\models;

use Yii;
use app\models\OrdersItem;
use app\models\Product;

/**
 * This is the model class for table "orders".
 *
 * @property int $id
 * @property int $company_id
 * @property string $order_date
 * @property string $summa Сума
 * @property string $coord_x Координата X
 * @property string $coord_y Координата Y
 * @property int $time_last Время до прибытия
 * @property string $distance Расстояние до места
 * @property int $time_max Время на заказ
 * @property int $status
 * @property string car_type Марка автомобиля
 * @property string car_model Модель автомобиля
 * @property string car_number Госномер автомобиля
 * @property string car_color Цвет автомобиля
 * @property string pay
 *
 * @property Company $company
 * @property OrdersItem[] $ordersItems
 */
class Orders extends \yii\db\ActiveRecord
{
    public $items;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'orders';
    }
    
    const ORDER_PRELIMINARY = '0';
    const ORDER_NEW = '1';
    const ORDER_WORK = '2';
    const ORDER_DELIVERY = '3';
    const ORDER_COMPLETE = '4';        
    //Предварительный/Новый/В работе/В доставке/Выполнен

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['company_id','client_id', 'time_max', 'status'], 'integer'],
            [['time_last','order_date'], 'safe'],
            [['summa', 'distance'], 'number'],
            [['car_type', 'car_model', 'car_number' , 'car_color' ],'string'],
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => Company::className(), 'targetAttribute' => ['company_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'company_id' => 'Комания',
            'order_date' => 'Дата заказа',
            'summa' => 'Сума',
            'time_last' => 'Время до прибытия',
            'distance' => 'Расстояние до места',
            'time_max' => 'Время на заказ',
            'status' => 'Статус',
            'car_type'=> 'Марка автомобиля',
            'car_model' => 'Модель автомобиля',
            'car_number' => 'Госномер автомобиля',
            'car_color'=> 'Цвет автомобиля',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(Company::className(), ['id' => 'company_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrdersItems()
    {
        return $this->hasMany(OrdersItem::className(), ['orders_id' => 'id']);
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getClients()
    {
        return $this->hasOne(Clients::className(), ['id' => 'client_id']);
    }
    
    /**
     * Возвращает список статусов
     * @return type
     */
    
    public static function getStatuses()
    {
        return [
            self::ORDER_PRELIMINARY => 'Предварительный',
            self::ORDER_NEW => 'Новый',
            self::ORDER_WORK => 'В работе',
            self::ORDER_DELIVERY => 'В доставке',
            self::ORDER_COMPLETE => 'Выполнен',
        ];
    }

    
    /**
     * Получить имя статуса. 
     * @param type $role
     * @return string
     */
    public static function getNameStatus($role)
    {
        switch ($role) {
            case 0: return "Предварительный";
            case 1: return "Новый";
            case 2: return "В работе";
            case 3: return "В доставке";
            case 4: return "Выполнен";
            default: return "Неизвестно";
        }
    }
    
    /**
     * Добавляет товар в заказ
     * @return type
     */
    public function addItem()
    {
        $allSumma=0;
        $maxTime=0;
        foreach ($this->items as $value) {
            $item = new OrdersItem();
            $item->orders_id= $this->id;
            $item->product_id = $value['product_id'];
            $item->amount = $value['amount'];
            $cena = Product::find()->where(['id'=>$value['product_id']])->one();
            if ($cena->time_prepare>$maxTime) {
                $maxTime=$cena->time_prepare;
            }
            $item->summa = $value['amount']*$cena->price;
            $item->save();
            $allSumma+=$value['amount']*$cena->price;
        }
        $this->summa=$allSumma;
        $this->time_max=$maxTime;
        return $this->save();
    }
    
    /**
     * Удаляет
     */
    public function deleteItem()
    {
        $items = OrdersItem::find()->where(['orders_id'=> $this->id])->all();
        foreach ($items as $value) {
            if (($rel = OrdersItem::findOne($value->id)) !== null) {
               $rel->delete();
            }
        }
    }
}

controllers/OrdersController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Orders;
use app\models\OrdersSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;
use yii\filters\AccessControl;
use app\models\Params;
use app\models\Clients;
use app\models\Company;

/**
 * OrdersController implements the CRUD actions for Orders model.
 */
class OrdersController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Orders models.
     * @return mixed
     */
    public function actionIndex()
    {    
        $searchModel = new OrdersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    /**
     * Displays a single Orders model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {   $model = $this->findModel($id);
        $client = Clients::find()->where(['id'=>$model->client_id])->one();
        $company = Company::find()->where(['id'=>$model->company_id])->one();
            return $this->render('viewmap', [
                'model' => $model,
                'client' => $client,
                'company' => $company,
            ]);
    }



    /**
     * Updates an existing Orders model.
     * For ajax request will return json object
     * and for non-ajax request if update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);       

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet){
                return [
                    'title'=> "Изменить заказ #".$id,
                    'content'=>$this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-primary pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn-info','type'=>"submit"])
                ];         
            }else if($model->load($request->post()) && $model->save()){
                $this->sendPush($model->client_id,$model->status);
                return [
                    'forceReload'=>'#crud-datatable-pjax',
                    'title'=> "Заказ #".$id,
                    'content'=>$this->renderAjax('view', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-primary pull-left','data-dismiss'=>"modal"]).
                            Html::a('Изменить',['update','id'=>$id],['class'=>'btn btn-warning','role'=>'modal-remote'])
                ];    
            }else{
                 return [
                    'title'=> "Изменить заказ #".$id,
                    'content'=>$this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-primary pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn-info','type'=>"submit"])
                ];        
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                $this->sendPush($model->client_id,$model->status);
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        }
    }
    
    public function actionChangeStatus()
    {
        if (Yii::$app->request->isAjax) {
            \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            $id = (int) Yii::$app->request->post('id');
            $status = (int) Yii::$app->request->post('status');
            $order = Orders::findOne($id);
            if ($order) {
                $order->status = $status;
                $order->save();
                return ['status'=>$id];
            } else {
                return ['status'=>$id];
            }
        }
    }

 
    /**
     * Finds the Orders model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Orders the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Orders::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
  protected function sendPush($client_id,$status)
    {
        $client = Clients::find()->where(['id'=>$client_id])->one();
        $param = Params::find()->one();
        $message['type'] = 'order_status';
        $message['order_status'] = $status;
        $url = 'https://gcm-http.googleapis.com/gcm/send';
        $fields = [
            'registration_ids' => [$client->key_push],
            'data' => ["message" => $message],
        ];

        $headers = [
            'Authorization: key='.$param->key_push,
            'Content-Type: application/json',
        ];

        // Open connection
        $ch = curl_init();
        // Set the url, number of POST vars, POST data
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($fields));
        // Execute post
        $result = curl_exec($ch);
        $client->push_result=$result;
        $client->save();
        // Close connection
        curl_close($ch);
        //echo $message;
    }
}

views/orders/_columns.php
<?php
use yii\helpers\Url;
use app\models\Orders;
use app\models\Company;



return [
    [
        'class' => 'kartik\grid\CheckboxColumn',
        'width' => '20px',
    ],
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
//    [
//        'class'=>'\kartik\grid\DataColumn',
//        'attribute'=>'company_id',
//        'filter'=> Company::getAllCompany(),
//        'value'=>'company.name',
//    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'order_date',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'summa',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'car_type',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'car_number',
    ],
    
//     [
//         'class'=>'\kartik\grid\DataColumn',
//         'format'=>'datetime',
//         'attribute'=>'time_last',
//     ],
//     [
//         'class'=>'\kartik\grid\DataColumn',
//         'attribute'=>'distance',
//     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'time_max',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'status',
         'filter'=> Orders::getStatuses(),
         'format'=>'raw',
         'value'=>function ($data) {
            return \kartik\helpers\Html::dropDownList('status'.$data->id, $data->status, Orders::getStatuses(),['id'=>'idstatus'.$data->id, 'onChange'=>'changeStatus('.$data->id.')']);
         }
     ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'dropdown' => false,
        'template' =>'{view}',
        'vAlign'=>'middle',
        'urlCreator' => function($action, $model, $key, $index) { 
                return Url::to([$action,'id'=>$key]);
        },
        'viewOptions'=>['label'=>'<button class="btn btn-info btn-xs"><span class="glyphicon glyphicon-eye-open"></span></button>','title'=>'Просмотр','target'=>'_blank','data-pjax'=>"0"],
        'updateOptions'=>['label'=>'<button class="btn btn-warning btn-xs"><span class="glyphicon glyphicon-pencil"></span></button>','role'=>'modal-remote','title'=>'Изменить', 'data-toggle'=>'tooltip'],
        'deleteOptions'=>['role'=>'modal-remote','title'=>'Удалить', 
                          'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                          'data-request-method'=>'post',
                          'label'=>'<button class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-trash"></span></button>',
                          'data-toggle'=>'tooltip',
                          'data-confirm-title'=>'Вы уверенны?',
                          'data-confirm-message'=>'Вы действительно хотите удалить запись'], 
    ],

];   

views/orders/_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Orders;

/* @var $this yii\web\View */
/* @var $model app\models\Orders */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="orders-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'status')->dropDownList(Orders::getStatuses()) ?>

  
	<?php if (!Yii::$app->request->isAjax){ ?>
	  	<div class="form-group">
	        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
	    </div>
	<?php } ?>

    <?php ActiveForm::end(); ?>
    
</div>

views/orders/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Orders */

?>
<div class="orders-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/orders/index.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset; 
use johnitvn\ajaxcrud\BulkButtonWidget;

/* @var $this yii\web\View */
/* @var $searchModel app\models\OrdersSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Orders';
$this->params['breadcrumbs'][] = $this->title;

CrudAsset::register($this);

?>
<div class="orders-index">
    <div id="ajaxCrudDatatable">
        <?=GridView::widget([
            'id'=>'crud-datatable',
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'pjax'=>true,
            'columns' => require(__DIR__.'/_columns.php'),
            'toolbar'=> [
                ['content'=>
                    '<div style="margin-top:10px;">' .
                    '<ul class="panel-controls">
                        <li><a href="#" class="panel-fullscreen"><span class="fa fa-expand"></span></a></li>
                        <li><a href="#" class="panel-refresh"><span class="fa fa-refresh"></span></a></li>
                        <li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
                    </ul>  '.
                    '</div>'
                ],
            ],          
            'striped' => true,
            'condensed' => true,
            'responsive' => true,          
            'panel' => [
                'type' => 'warning', 
                'heading' => '<i class="glyphicon glyphicon-list"></i> Список заказов',
                'before'=>'',
                'after'=>'',
            ]
        ])?>
    </div>
</div>

<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>

    <script>
    function changeStatus(id){
        
        var status = $("#idstatus"+id).val();
        
    $.ajax({
       url: 'change-status',
       type: 'post',
        data: {id:id, status:status},
       success: function (data) {
           console.log(data.status);
          
       }
  });    
    }
    
    </script>

views/orders/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Orders */
?>
<div class="orders-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/orders/viewmap.php
<?php

use yii\helpers\Html;
use yii\bootstrap\Modal;
use johnitvn\ajaxcrud\CrudAsset; 
use app\models\Orders;

CrudAsset::register($this);
/* @var $this yii\web\View */
/* @var $model app\models\Orders */
/* @var $company app\models\Company */
/* @var $client app\models\Clients */
?>

<div id="ajaxCrudDatatable">
    
<div class="orders-view">
    <div class="box box-default" style="margin-top: 30px;margin-bottom: 20px">
        <div class="box-body">
            <div class="row">
                <?php if ($model->status != Orders::ORDER_COMPLETE ) :?>
                <div class="col-md-7">
                    <div id="map">
                    </div>
                </div>     
                <?php endif;?>
                
                <div class="col-md-5">
                    <div class="panel panel-success panel-hidden-controls">
                        <div class="panel-heading ui-draggable-handle">
                            <h1 class="panel-title"> <i class="fa fa-asterisk"> </i> Информация о заказе </h1>
                            <?=Html::a('Редактировать &nbsp;<i class="glyphicon glyphicon-pencil"></i>',['/orders/update','id'=>$model->id],[
                                    'class'=>"btn btn-warning btn-rounded pull-right",
                                    'title'=>"Редактировать",
                                    'role'=>"modal-remote",
                            ])?>
                        </div>    
                        <div class="panel-body">
                            <p><b><?=$model->getAttributeLabel('company_id')?></b> : <?=Html::encode($model->company->name)?></p>
                            <p><b><?=$model->getAttributeLabel('order_date')?></b> : <?=Html::encode($model->order_date)?></p>
                            <p><b>Имя клиента</b> : <?=Html::encode($model->clients->name)?></p>
                            <p><b>Телефон</b> : <?=Html::encode($model->clients->phone)?></p>
                            <hr>
                            <p><b><?=$model->getAttributeLabel('summa')?></b> : <?=Html::encode($model->summa)?></p>
                            <p><b><?=$model->getAttributeLabel('time_last')?></b> : <span id="time-last"></span></p>
                            <p><b><?=$model->getAttributeLabel('distance')?></b> : <span id="distance"></span></p>
                            <p><b><?=$model->getAttributeLabel('time_max')?></b> : <?=Html::encode($model->time_max)?></p>
                        </div>
                    </div>
                    <div class="panel panel-success panel-hidden-controls">
                        <div class="panel-heading ui-draggable-handle">
                            <h1 class="panel-title"> <i class="fa fa-user"> </i> Личная информация </h1>
                            <ul class="panel-controls">
                                <li><a href="#" class="panel-collapse"><span class="fa fa-angle-down"></span></a></li>
                                <li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
                            </ul>
                        </div>    
                        <div class="panel-body">
                            <p><b><?=$model->getAttributeLabel('car_type')?></b> : <?=Html::encode($model->car_type)?></p>
                            <p><b><?=$model->getAttributeLabel('car_model')?></b> : <?=Html::encode($model->car_model)?></p>
                            <p><b><?=$model->getAttributeLabel('car_number')?></b> : <?=Html::encode($model->car_number)?></p>
                            <p><b><?=$model->getAttributeLabel('car_color')?></b> : <?=Html::encode($model->car_color)?></p>
                        </div>
                    </div>
                    <div class="panel panel-success panel-hidden-controls">
                        <div class="panel-heading ui-draggable-handle">
                            <h1 class="panel-title"> <i class="fa fa-list"> </i> Информация о товаре </h1>
                            <ul class="panel-controls">
                                <li><a href="#" class="panel-collapse"><span class="fa fa-angle-down"></span></a></li>
                                <li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
                            </ul>
                        </div>    
                        <div class="panel-body">
                            <div class=table-responsive">
                                <table class="table table-bordered" >
                                    <thead>
                                        <tr>
                                            <th style="width: 60%">Товар</th>
                                            <th style="width: 20%">К-во</th>
                                            <th style="width: 20%">Сумма</th>        
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($model->ordersItems as $item) :?>
                                        <tr>
                                            <td ><?=Html::encode($item->product->name)?></td>
                                            <td ><?=Html::encode($item->amount)?></td>
                                            <td ><?=Html::encode($item->summa)?></td>
                                        </tr>
                                        <?php endforeach;?>
                                    </tbody>
                                </table>  
                            </div>
                        </div>
                    </div>
                </div>        
            </div>
        </div>
    </div>
</div>
</div>
    <script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU&amp;apikey=&lt;ваш API-ключ&gt;" type="text/javascript"></script>
	<style>
         #map {
            width: 100%; height: 600px; padding: 0; margin: 0;
        }
    </style>
    <style>
        .YMaps-layer-container img{
max-width: none;
}
    </style>

<script>
function init () {
    /**
     * Создаем мультимаршрут.
     * Первым аргументом передаем модель либо объект описания модели.
     * Вторым аргументом передаем опции отображения мультимаршрута.
     * @see https://api.yandex.ru/maps/doc/jsapi/2.1/ref/reference/multiRouter.MultiRoute.xml
     * @see https://api.yandex.ru/maps/doc/jsapi/2.1/ref/reference/multiRouter.MultiRouteModel.xml
     */
    
    
    var multiRoute = new ymaps.multiRouter.MultiRoute({
        // Описание опорных точек мультимаршрута.
        referencePoints: [
            [<?=$company->coord_x?>,<?=$company->coord_y?>],
            [<?=$client->coord_x?>,<?=$client->coord_y?>],
        ],
        // Параметры маршрутизации.
        params: {
            // Ограничение на максимальное количество маршрутов, возвращаемое маршрутизатором.
            results: 1,
            avoidTrafficJams: true,
        }
    }, {
        // Автоматически устанавливать границы карты так, чтобы маршрут был виден целиком.
        boundsAutoApply: true,
        wayPointStartIconLayout: "default#image",
        wayPointStartIconImageHref: "/img/burger.png",
        wayPointStartIconImageSize: [40, 40],
        wayPointStartIconImageOffset: [-20, -20],
        // Задаем собственную картинку для последней путевой точки.
        wayPointFinishIconLayout: "default#image",
        wayPointFinishIconImageHref: "/img/car.png",
        wayPointFinishIconImageSize: [40, 40],
        wayPointFinishIconImageOffset: [-20, -20],
        
    });

    

    // Создаем карту с добавленными на нее кнопками.
    var myMap = new ymaps.Map('map', {
        center: [55.750625, 37.626],
        zoom: 7,
    }, {
        buttonMaxWidth: 300
    });

    // Добавляем мультимаршрут на карту.
    myMap.geoObjects.add(multiRoute);
    multiRoute.model.events.add("requestsuccess", function (event) {

console.log(multiRoute.getRoutes().get(0).properties.get("distance").value);
$("#time-last").html(multiRoute.getRoutes().get(0).properties.get("duration").text);
$("#distance").html(multiRoute.getRoutes().get(0).properties.get("distance").text);

});
    
}

ymaps.ready(init);
</script>
<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>